# Generated by Django 3.0.4 on 2021-01-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='asset',
            field=models.IntegerField(default=60, verbose_name='account asset'),
        ),
    ]
