# Generated by Django 3.0.4 on 2021-01-07 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Device')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Place')),
            ],
        ),
    ]
