# Generated by Django 3.0.4 on 2021-01-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='end_time',
            field=models.BigIntegerField(verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='start_time',
            field=models.BigIntegerField(verbose_name='start time'),
        ),
    ]
